package com.example.Orientation.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
public class Admin{

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Long admin_id;
	@Column(name = "email", nullable = false)
	private String email;
	@Column(name = "password", nullable = false)
	private String password;

	public Admin() {
	}

	
	public Long getAdmin_id() {
		return admin_id;
	}


	public void setAdmin_id(Long admin_id) {
		this.admin_id = admin_id;
	}


	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	

}
