package com.example.Orientation.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Branchesp generated by hbm2java
 */
@Entity
public class Branchesp {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Long branchesp_id;
	private String bs;

    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)
	@JoinColumn(name="branche_id", nullable=false)
	private Branche branche;

	public Branchesp() {
	}

	public Long getBranchesp_id() {
		return branchesp_id;
	}

	public void setBranchesp_id(Long branchesp_id) {
		this.branchesp_id = branchesp_id;
	}

	public String getBs() {
		return bs;
	}

	public void setBs(String bs) {
		this.bs = bs;
	}

	public Branche getBranche() {
		return branche;
	}

	public void setBranche(Branche branche) {
		this.branche = branche;
	}

	
}
