package com.example.Orientation.entities;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.ManyToAny;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Branche generated by hbm2java
 */
@Entity
public class Branche {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Long branche_id;
	private String nom_branche;
	@OneToMany(mappedBy = "branche", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonProperty(access = Access.WRITE_ONLY)
	private Set<Brancheetablissement> brancheetablissements = new HashSet<Brancheetablissement>(0);

	@OneToMany(mappedBy = "branche")
    @JsonProperty(access = Access.WRITE_ONLY)
	private Set<Branchesp> branchesp = new HashSet<Branchesp>(0);
	
	@ManyToOne
	@JoinColumn(name = "formation_id", nullable = true)
	private Formation formation;


	public Branche() {
	}


	public Long getBranche_id() {
		return branche_id;
	}


	public void setBranche_id(Long branche_id) {
		this.branche_id = branche_id;
	}


	public String getNom_branche() {
		return nom_branche;
	}


	public void setNom_branche(String nom_branche) {
		this.nom_branche = nom_branche;
	}


	public Set<Brancheetablissement> getBrancheetablissements() {
		return brancheetablissements;
	}


	public void setBrancheetablissements(Set<Brancheetablissement> brancheetablissements) {
		this.brancheetablissements = brancheetablissements;
	}


	public Set<Branchesp> getBranchesp() {
		return branchesp;
	}


	public void setBranchesp(Set<Branchesp> branchesp) {
		this.branchesp = branchesp;
	}
	
	

}
