package com.example.Orientation.entities;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Brancheetablissement generated by hbm2java
 */
@Entity
public class Brancheetablissement {

	@EmbeddedId
	private BrancheetablissementId id;
	
	@ManyToOne
	@MapsId("branche_id")
	@JsonIgnore
	private Branche branche;
	
	@ManyToOne
	@MapsId("etablissement_id")
	@JsonIgnore
	private Etablissement etablissement;

	public Brancheetablissement() {
	}

	public BrancheetablissementId getId() {
		return id;
	}

	public void setId(BrancheetablissementId id) {
		this.id = id;
	}

	public Branche getBranche() {
		return branche;
	}

	public void setBranche(Branche branche) {
		this.branche = branche;
	}

	public Etablissement getEtablissement() {
		return etablissement;
	}

	public void setEtablissement(Etablissement etablissement) {
		this.etablissement = etablissement;
	}
	
	

}
