package com.example.Orientation.entities;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Candidat generated by hbm2java
 */
@Entity
public class Candidat  {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Long candidat_id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "maladie_id", nullable = false)
	private Maladie maladie;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "riasec_id", nullable = false)
	private Riasec riasec;
	private String nom;
	private String prenom;
	private String adress;
	private String sex;
	private float taille;
	private double tel;
	private String filiere;
	private boolean operation;
	private String email;
	@Lob
	@Column(columnDefinition = "MEDIUMBLOB")
	private String image;
	
	private String password;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "filiere_id", nullable = true)
	private Filiere monf;
	
	@ManyToOne
	@JoinColumn(name = "projet_id", nullable = true)
	private Projet projet;

	
	public Filiere getMonf() {
		return monf;
	}

	public void setMonf(Filiere monf) {
		this.monf = monf;
	}

	public Projet getProjet() {
		return projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	public Candidat() {
	}

	public Long getCandidat_id() {
		return candidat_id;
	}

	public void setCandidat_id(Long candidat_id) {
		this.candidat_id = candidat_id;
	}

	public Maladie getMaladie() {
		return maladie;
	}

	public void setMaladie(Maladie maladie) {
		this.maladie = maladie;
	}

	public Riasec getRiasec() {
		return riasec;
	}

	public void setRiasec(Riasec riasec) {
		this.riasec = riasec;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getAdress() {
		return adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public float getTaille() {
		return taille;
	}

	public void setTaille(float taille) {
		this.taille = taille;
	}

	public double getTel() {
		return tel;
	}

	public void setTel(double tel) {
		this.tel = tel;
	}

	public String getFiliere() {
		return filiere;
	}

	public void setFiliere(String filiere) {
		this.filiere = filiere;
	}

	public boolean isOperation() {
		return operation;
	}

	public void setOperation(boolean operation) {
		this.operation = operation;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	
	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}




}
