package com.example.Orientation.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Genre generated by hbm2java
 */
@Entity
public class Genre  {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Long id;
	private String nom_genre;
	@OneToMany(mappedBy = "genre")
	@JsonIgnore
	private Set<Etablissement> etablissements = new HashSet<Etablissement>(0);

	public Genre() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNom_genre() {
		return nom_genre;
	}

	public void setNom_genre(String nom_genre) {
		this.nom_genre = nom_genre;
	}

	public Set<Etablissement> getEtablissements() {
		return etablissements;
	}

	public void setEtablissements(Set<Etablissement> etablissements) {
		this.etablissements = etablissements;
	}

	

}
