package com.example.Orientation.entities;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MetierformationId generated by hbm2java
 */
@Embeddable
public class MetierformationId implements java.io.Serializable {
	@Column
	private Long metier;
	@Column
	private Long formation;

	public MetierformationId() {
	}

	

}
