package com.example.Orientation.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Pays generated by hbm2java
 */
@Entity
public class Pays implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Long  pays_id;

	private String nom_pays;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pays")
	@JsonIgnore
	private Set<Region> regions = new HashSet<Region>(0);

	public Pays() {
	}

	public Long getPays_id() {
		return pays_id;
	}

	public void setPays_id(Long pays_id) {
		this.pays_id = pays_id;
	}

	public String getNom_pays() {
		return nom_pays;
	}

	public void setNom_pays(String nom_pays) {
		this.nom_pays = nom_pays;
	}

	public Set<Region> getRegions() {
		return regions;
	}

	public void setRegions(Set<Region> regions) {
		this.regions = regions;
	}
	
	

}
