package com.example.Orientation.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Region generated by hbm2java
 */
@Entity
public class Region {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Long region_id;

@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pays_id", nullable = false)
	private Pays pays;
	private byte[] region;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	@JsonIgnore
	private Set<Ville> villes = new HashSet<Ville>(0);

	public Region() {
	}

	public Long getRegion_id() {
		return region_id;
	}

	public void setRegion_id(Long region_id) {
		this.region_id = region_id;
	}

	
	

	public Pays getPays() {
		return pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	public byte[] getRegion() {
		return region;
	}

	public void setRegion(byte[] region) {
		this.region = region;
	}

	public Set<Ville> getVilles() {
		return villes;
	}

	public void setVilles(Set<Ville> villes) {
		this.villes = villes;
	}

	
	

}
