package com.example.Orientation.entities;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Riasec generated by hbm2java
 */
@Entity
public class Riasec {

@Id
	@GeneratedValue(strategy = IDENTITY)
	private Long riasec_id;
	private String codeRiasec;
	@OneToMany(mappedBy = "riasec", cascade = CascadeType.ALL, orphanRemoval = true)
	@JsonIgnore	
	private Set<Riasecmetier> riasecmetiers = new HashSet<Riasecmetier>(0);

	public Riasec() {
	}

	public Long getRiasec_id() {
		return riasec_id;
	}

	public void setRiasec_id(Long riasec_id) {
		this.riasec_id = riasec_id;
	}

	public String getCodeRiasec() {
		return codeRiasec;
	}

	public void setCodeRiasec(String codeRiasec) {
		this.codeRiasec = codeRiasec;
	}

	public Set<Riasecmetier> getRiasecmetiers() {
		return riasecmetiers;
	}

	public void setRiasecmetiers(Set<Riasecmetier> riasecmetiers) {
		this.riasecmetiers = riasecmetiers;
	}
	
	

	

}
