package com.example.Orientation.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Secteur generated by hbm2java
 */
@Entity
public class Secteur {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Long secteur_id;
	private String nsecteur;
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "secteur")
		@JsonIgnore
	private Set<Metier> metiers = new HashSet<Metier>(0);

	public Secteur() {
	}

	public Secteur(String secteur) {
		this.nsecteur = secteur;
	}

	public Long getSecteur_id() {
		return secteur_id;
	}

	public void setSecteur_id(Long secteur_id) {
		this.secteur_id = secteur_id;
	}

	

	public String getNsecteur() {
		return nsecteur;
	}

	public void setNsecteur(String nsecteur) {
		this.nsecteur = nsecteur;
	}

	public Set<Metier> getMetiers() {
		return metiers;
	}

	public void setMetiers(Set<Metier> metiers) {
		this.metiers = metiers;
	}


}
