package com.example.Orientation.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Type generated by hbm2java
 */
@Entity
public class Type implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Long type_id;
	private String ntype;
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
@JsonIgnore
	private Set<Etablissement> etablissements = new HashSet<Etablissement>(0);

	public Type() {
	}

	public Long getType_id() {
		return type_id;
	}

	public void setType_id(Long type_id) {
		this.type_id = type_id;
	}

	
	public String getNtype() {
		return ntype;
	}

	public void setNtype(String ntype) {
		this.ntype = ntype;
	}

	public Set<Etablissement> getEtablissements() {
		return etablissements;
	}

	public void setEtablissements(Set<Etablissement> etablissements) {
		this.etablissements = etablissements;
	}
	
	
}
